/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: addressbook.proto */

#ifndef PROTOBUF_C_addressbook_2eproto__INCLUDED
#define PROTOBUF_C_addressbook_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _PhoneNumber PhoneNumber;
typedef struct _Person Person;
typedef struct _Book Book;
typedef struct _AddressBook AddressBook;


/* --- enums --- */

typedef enum _PhoneNumber__PhoneType {
  PHONE_NUMBER__PHONE_TYPE__MOBILE = 0,
  PHONE_NUMBER__PHONE_TYPE__HOME = 1,
  PHONE_NUMBER__PHONE_TYPE__WORK = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(PHONE_NUMBER__PHONE_TYPE)
} PhoneNumber__PhoneType;

/* --- messages --- */

struct  _PhoneNumber
{
  ProtobufCMessage base;
  char *number;
  PhoneNumber__PhoneType type;
};
#define PHONE_NUMBER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&phone_number__descriptor) \
    , NULL, 0 }


struct  _Person
{
  ProtobufCMessage base;
  char *name;
  int32_t id;
  char *email;
  PhoneNumber *phone;
};
#define PERSON__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&person__descriptor) \
    , NULL, 0, NULL, NULL }


struct  _Book
{
  ProtobufCMessage base;
  char *name;
};
#define BOOK__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&book__descriptor) \
    , NULL }


struct  _AddressBook
{
  ProtobufCMessage base;
  size_t n_people;
  Person **people;
  size_t n_book;
  Book **book;
};
#define ADDRESS_BOOK__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&address_book__descriptor) \
    , 0,NULL, 0,NULL }


/* PhoneNumber methods */
void   phone_number__init
                     (PhoneNumber         *message);
size_t phone_number__get_packed_size
                     (const PhoneNumber   *message);
size_t phone_number__pack
                     (const PhoneNumber   *message,
                      uint8_t             *out);
size_t phone_number__pack_to_buffer
                     (const PhoneNumber   *message,
                      ProtobufCBuffer     *buffer);
PhoneNumber *
       phone_number__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   phone_number__free_unpacked
                     (PhoneNumber *message,
                      ProtobufCAllocator *allocator);
/* Person methods */
void   person__init
                     (Person         *message);
size_t person__get_packed_size
                     (const Person   *message);
size_t person__pack
                     (const Person   *message,
                      uint8_t             *out);
size_t person__pack_to_buffer
                     (const Person   *message,
                      ProtobufCBuffer     *buffer);
Person *
       person__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   person__free_unpacked
                     (Person *message,
                      ProtobufCAllocator *allocator);
/* Book methods */
void   book__init
                     (Book         *message);
size_t book__get_packed_size
                     (const Book   *message);
size_t book__pack
                     (const Book   *message,
                      uint8_t             *out);
size_t book__pack_to_buffer
                     (const Book   *message,
                      ProtobufCBuffer     *buffer);
Book *
       book__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   book__free_unpacked
                     (Book *message,
                      ProtobufCAllocator *allocator);
/* AddressBook methods */
void   address_book__init
                     (AddressBook         *message);
size_t address_book__get_packed_size
                     (const AddressBook   *message);
size_t address_book__pack
                     (const AddressBook   *message,
                      uint8_t             *out);
size_t address_book__pack_to_buffer
                     (const AddressBook   *message,
                      ProtobufCBuffer     *buffer);
AddressBook *
       address_book__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   address_book__free_unpacked
                     (AddressBook *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*PhoneNumber_Closure)
                 (const PhoneNumber *message,
                  void *closure_data);
typedef void (*Person_Closure)
                 (const Person *message,
                  void *closure_data);
typedef void (*Book_Closure)
                 (const Book *message,
                  void *closure_data);
typedef void (*AddressBook_Closure)
                 (const AddressBook *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor phone_number__descriptor;
extern const ProtobufCEnumDescriptor    phone_number__phone_type__descriptor;
extern const ProtobufCMessageDescriptor person__descriptor;
extern const ProtobufCMessageDescriptor book__descriptor;
extern const ProtobufCMessageDescriptor address_book__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_addressbook_2eproto__INCLUDED */
