/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: addressbook.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "addressbook.pb-c.h"
void   phone_number__init
                     (PhoneNumber         *message)
{
  static PhoneNumber init_value = PHONE_NUMBER__INIT;
  *message = init_value;
}
size_t phone_number__get_packed_size
                     (const PhoneNumber *message)
{
  assert(message->base.descriptor == &phone_number__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t phone_number__pack
                     (const PhoneNumber *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &phone_number__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t phone_number__pack_to_buffer
                     (const PhoneNumber *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &phone_number__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PhoneNumber *
       phone_number__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PhoneNumber *)
     protobuf_c_message_unpack (&phone_number__descriptor,
                                allocator, len, data);
}
void   phone_number__free_unpacked
                     (PhoneNumber *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &phone_number__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   person__init
                     (Person         *message)
{
  static Person init_value = PERSON__INIT;
  *message = init_value;
}
size_t person__get_packed_size
                     (const Person *message)
{
  assert(message->base.descriptor == &person__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t person__pack
                     (const Person *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &person__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t person__pack_to_buffer
                     (const Person *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &person__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Person *
       person__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Person *)
     protobuf_c_message_unpack (&person__descriptor,
                                allocator, len, data);
}
void   person__free_unpacked
                     (Person *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &person__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   book__init
                     (Book         *message)
{
  static Book init_value = BOOK__INIT;
  *message = init_value;
}
size_t book__get_packed_size
                     (const Book *message)
{
  assert(message->base.descriptor == &book__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t book__pack
                     (const Book *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &book__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t book__pack_to_buffer
                     (const Book *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &book__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Book *
       book__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Book *)
     protobuf_c_message_unpack (&book__descriptor,
                                allocator, len, data);
}
void   book__free_unpacked
                     (Book *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &book__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   address_book__init
                     (AddressBook         *message)
{
  static AddressBook init_value = ADDRESS_BOOK__INIT;
  *message = init_value;
}
size_t address_book__get_packed_size
                     (const AddressBook *message)
{
  assert(message->base.descriptor == &address_book__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t address_book__pack
                     (const AddressBook *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &address_book__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t address_book__pack_to_buffer
                     (const AddressBook *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &address_book__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AddressBook *
       address_book__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AddressBook *)
     protobuf_c_message_unpack (&address_book__descriptor,
                                allocator, len, data);
}
void   address_book__free_unpacked
                     (AddressBook *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &address_book__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue phone_number__phone_type__enum_values_by_number[3] =
{
  { "MOBILE", "PHONE_NUMBER__PHONE_TYPE__MOBILE", 0 },
  { "HOME", "PHONE_NUMBER__PHONE_TYPE__HOME", 1 },
  { "WORK", "PHONE_NUMBER__PHONE_TYPE__WORK", 2 },
};
static const ProtobufCIntRange phone_number__phone_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex phone_number__phone_type__enum_values_by_name[3] =
{
  { "HOME", 1 },
  { "MOBILE", 0 },
  { "WORK", 2 },
};
const ProtobufCEnumDescriptor phone_number__phone_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "PhoneNumber.PhoneType",
  "PhoneType",
  "PhoneNumber__PhoneType",
  "",
  3,
  phone_number__phone_type__enum_values_by_number,
  3,
  phone_number__phone_type__enum_values_by_name,
  1,
  phone_number__phone_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor phone_number__field_descriptors[2] =
{
  {
    "number",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(PhoneNumber, number),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(PhoneNumber, type),
    &phone_number__phone_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned phone_number__field_indices_by_name[] = {
  0,   /* field[0] = number */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange phone_number__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor phone_number__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PhoneNumber",
  "PhoneNumber",
  "PhoneNumber",
  "",
  sizeof(PhoneNumber),
  2,
  phone_number__field_descriptors,
  phone_number__field_indices_by_name,
  1,  phone_number__number_ranges,
  (ProtobufCMessageInit) phone_number__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor person__field_descriptors[4] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Person, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Person, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "email",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Person, email),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "phone",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Person, phone),
    &phone_number__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned person__field_indices_by_name[] = {
  2,   /* field[2] = email */
  1,   /* field[1] = id */
  0,   /* field[0] = name */
  3,   /* field[3] = phone */
};
static const ProtobufCIntRange person__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor person__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Person",
  "Person",
  "Person",
  "",
  sizeof(Person),
  4,
  person__field_descriptors,
  person__field_indices_by_name,
  1,  person__number_ranges,
  (ProtobufCMessageInit) person__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor book__field_descriptors[1] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Book, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned book__field_indices_by_name[] = {
  0,   /* field[0] = name */
};
static const ProtobufCIntRange book__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor book__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Book",
  "Book",
  "Book",
  "",
  sizeof(Book),
  1,
  book__field_descriptors,
  book__field_indices_by_name,
  1,  book__number_ranges,
  (ProtobufCMessageInit) book__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor address_book__field_descriptors[2] =
{
  {
    "people",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(AddressBook, n_people),
    offsetof(AddressBook, people),
    &person__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "book",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(AddressBook, n_book),
    offsetof(AddressBook, book),
    &book__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned address_book__field_indices_by_name[] = {
  1,   /* field[1] = book */
  0,   /* field[0] = people */
};
static const ProtobufCIntRange address_book__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor address_book__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "AddressBook",
  "AddressBook",
  "AddressBook",
  "",
  sizeof(AddressBook),
  2,
  address_book__field_descriptors,
  address_book__field_indices_by_name,
  1,  address_book__number_ranges,
  (ProtobufCMessageInit) address_book__init,
  NULL,NULL,NULL    /* reserved[123] */
};
